active_profile: local_sonnet
profiles:
  local_haiku:
    name: local_haiku
    driver: cli:claude
    model: haiku
    validator_model: haiku
    tracker: noop
    working_dir: /Users/ka/github/existential-birds/test_repo_c
  local_sonnet:
    name: local_sonnet
    driver: cli:claude
    model: anthropic:sonnet
    validator_model: anthropic:haiku
    tracker: noop
    working_dir: /Users/ka/github/existential-birds/test_repo_c
  local_opus:
    name: local_opus
    driver: cli:claude
    model: opus
    validator_model: anthropic:haiku
    tracker: noop
    working_dir: /Users/ka/github/existential-birds/test_repo_c
  api_minimax_m2:
    name: api_minimax_m2
    driver: api:openrouter
    model: minimax/minimax-m2
    validator_model: anthropic:haiku
    tracker: noop
    working_dir: /Users/ka/github/existential-birds/test_repo_c